g"""Add password reset columns to users

Revision ID: 002
Revises: 9c7d10deb489
Create Date: 2025-10-13 00:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '002'
down_revision = '9c7d10deb489'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password_reset_code', sa.Text(), nullable=True))
    op.add_column('users', sa.Column('password_reset_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('users', sa.Column('password_reset_requested_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'password_reset_requested_at')
    op.drop_column('users', 'password_reset_at')
    op.drop_column('users', 'password_reset_code')
    # ### end Alembic commands ###



