"""add project_members and review_assignments

Revision ID: 04917d61fe8f
Revises: 5fb4eea48ce3
Create Date: 2025-10-16 06:32:35.240338

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '04917d61fe8f'
down_revision = '5fb4eea48ce3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project_members',
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.CheckConstraint("role IN ('owner', 'member')", name='valid_role'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('project_id', 'user_id')
    )
    op.create_index('ix_project_members_project_id', 'project_members', ['project_id'], unique=False)
    op.create_index('ix_project_members_user_id', 'project_members', ['user_id'], unique=False)
    op.create_table('review_assignments',
    sa.Column('review_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['review_id'], ['reviews.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('review_id', 'user_id')
    )
    op.create_index('ix_review_assignments_review_id', 'review_assignments', ['review_id'], unique=False)
    op.create_index('ix_review_assignments_user_id', 'review_assignments', ['user_id'], unique=False)
    op.drop_index('ix_users_email', table_name='users')
    op.create_index('ix_users_email', 'users', ['email'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_users_email', table_name='users')
    op.create_index('ix_users_email', 'users', ['email'], unique=True)
    op.drop_index('ix_review_assignments_user_id', table_name='review_assignments')
    op.drop_index('ix_review_assignments_review_id', table_name='review_assignments')
    op.drop_table('review_assignments')
    op.drop_index('ix_project_members_user_id', table_name='project_members')
    op.drop_index('ix_project_members_project_id', table_name='project_members')
    op.drop_table('project_members')
    # ### end Alembic commands ###
