"""Add projects, reviews, checklists, and checklist_answers tables

Revision ID: 5fb4eea48ce3
Revises: 002
Create Date: 2025-10-14 05:10:05.049474

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '5fb4eea48ce3'
down_revision = '002'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('projects',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('owner_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_projects_id'), 'projects', ['id'], unique=False)
    op.create_index(op.f('ix_projects_owner_id'), 'projects', ['owner_id'], unique=False)
    op.create_table('reviews',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reviews_id'), 'reviews', ['id'], unique=False)
    op.create_index('ix_reviews_project_id', 'reviews', ['project_id'], unique=False)
    op.create_table('checklists',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('review_id', sa.UUID(), nullable=False),
    sa.Column('reviewer_id', sa.UUID(), nullable=True),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("type IN ('amstar')", name='check_checklist_type'),
    sa.ForeignKeyConstraint(['review_id'], ['reviews.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reviewer_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_checklists_id'), 'checklists', ['id'], unique=False)
    op.create_index(op.f('ix_checklists_review_id'), 'checklists', ['review_id'], unique=False)
    op.create_index('ix_checklists_reviewer_id', 'checklists', ['reviewer_id'], unique=False)
    op.create_table('checklist_answers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('checklist_id', sa.UUID(), nullable=False),
    sa.Column('question_key', sa.String(length=50), nullable=False),
    sa.Column('answers', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('critical', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['checklist_id'], ['checklists.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_checklist_answers_checklist_id', 'checklist_answers', ['checklist_id'], unique=False)
    op.create_index('ix_checklist_answers_checklist_question', 'checklist_answers', ['checklist_id', 'question_key'], unique=False)
    op.create_index(op.f('ix_checklist_answers_id'), 'checklist_answers', ['id'], unique=False)
    # op.drop_table('scores')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # op.create_table('scores',
    # sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    # sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    # sa.Column('value', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    # sa.PrimaryKeyConstraint('id', name='scores_pkey')
    # )
    op.drop_index(op.f('ix_checklist_answers_id'), table_name='checklist_answers')
    op.drop_index('ix_checklist_answers_checklist_question', table_name='checklist_answers')
    op.drop_index('ix_checklist_answers_checklist_id', table_name='checklist_answers')
    op.drop_table('checklist_answers')
    op.drop_index('ix_checklists_reviewer_id', table_name='checklists')
    op.drop_index(op.f('ix_checklists_review_id'), table_name='checklists')
    op.drop_index(op.f('ix_checklists_id'), table_name='checklists')
    op.drop_table('checklists')
    op.drop_index('ix_reviews_project_id', table_name='reviews')
    op.drop_index(op.f('ix_reviews_id'), table_name='reviews')
    op.drop_table('reviews')
    op.drop_index(op.f('ix_projects_owner_id'), table_name='projects')
    op.drop_index(op.f('ix_projects_id'), table_name='projects')
    op.drop_table('projects')
    # ### end Alembic commands ###
