"""Add email verification columns to users

Revision ID: 9c7d10deb489
Revises: 001
Create Date: 2025-10-02 01:50:27.117621

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9c7d10deb489'
down_revision = '001'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('email_verified_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('users', sa.Column('email_verification_code', sa.Text(), nullable=True))
    op.add_column('users', sa.Column('email_verification_requested_at', sa.DateTime(timezone=True), nullable=True))
    op.drop_index('ix_users_email', table_name='users')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.drop_column('users', 'is_active')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_index('ix_users_email', 'users', ['email'], unique=False)
    op.drop_column('users', 'email_verification_requested_at')
    op.drop_column('users', 'email_verification_code')
    op.drop_column('users', 'email_verified_at')
    # ### end Alembic commands ###
