"""add created_at to projects

Revision ID: f7c742f02751
Revises: 04917d61fe8f
Create Date: 2025-10-17 06:13:14.756858

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f7c742f02751'
down_revision = '04917d61fe8f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'created_at')

    # ### end Alembic commands ###
